# Generated by Django 3.2.4 on 2021-07-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskapi", "0004_auto_20210701_1034"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Survey"), (2, "Discussion"), (3, "Diary")], default=0
            ),
            preserve_default=False,
        ),
    ]
