# Generated by Django 3.2.4 on 2021-07-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskapi", "0005_task_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Live"), (2, "Pending"), (3, "Archived")]
                    ),
                ),
            ],
        ),
    ]
