# Generated by Django 2.2.24 on 2021-07-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapi', '0011_tile_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile',
            name='launch_date',
            field=models.DateField(null=True),
        ),
    ]
