# Generated by Django 2.2.24 on 2021-07-05 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taskapi", "0013_auto_20210705_1135"),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name="task",
            order_with_respect_to="tile",
        ),
    ]
