# Generated by Django 2.2.24 on 2021-07-09 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("taskapi", "0014_auto_20210705_1147"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="tile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="taskapi.Tile",
            ),
        ),
    ]
