# Generated by Django 2.2.24 on 2021-07-09 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taskapi", "0016_auto_20210709_1312"),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name="task",
            order_with_respect_to=None,
        ),
    ]
