# Generated by Django 2.2.24 on 2021-07-09 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapi', '0017_auto_20210709_1653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['tile']},
        ),
    ]
